title: Rafael Bizzo Blog
author: Rafael Bizzo
email: rafaplayrj2@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Um Simples Blog para quem gosta de tecnologia Linux e Open Souce
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Rafael Bizzo
  tagline: Linux e Open Source
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle

  # generate social links in footer
  social_links:
    twitter: _RafaelRJ_
    github:  rafaelbizzo
    # linkedIn: in/thelehhman
    rss: rss
    # dribbble: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # pinterest: jekyll
    youtube: channel/UCZXEBTBNwmdsvPNQFtRzZ6w
    # facebook: jekyll
    # soundcloud: jekyll
    # telegram: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
